from lightwood.encoders.categorical.onehot import OneHotEncoder
from lightwood.encoders.categorical.multihot import MultihotEncoder
from lightwood.encoders.categorical.autoencoder import CategoricalAutoEncoder
